runtime: python39

handlers:
  # Serve CSS files from /css/ and also style.css in root
  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  - url: /assets
    static_dir: assets

  - url: /style.css
    static_files: style.css
    upload: style.css

  # Serve image files (like a.jpg) from root
  - url: /(.*\.(jpg|jpeg|png|gif|svg))
    static_files: \1
    upload: (.*\.(jpg|jpeg|png|gif|svg))

  # Serve index.html as the main page
  - url: /.*
    static_files: index.html
    upload: index.html
